language: c

compiler:
    - gcc
    - clang

env:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DUNITTEST_VERBOSE=ON ..
    - make all
    - make unittest

addons:
    apt:
        sources:
            - kalakris-cmake
        packages:
            - cmake

before_install:
    - export CPPUTEST_VERSION=v3.8
    - export CPPUTEST=cpputest-${CPPUTEST_VERSION}
    - wget https://github.com/cpputest/cpputest/releases/download/${CPPUTEST_VERSION}/${CPPUTEST}.tar.gz
    - tar -xzvf *.tar.gz
    - cd ${CPPUTEST}
    - mkdir _build && cd _build
    - cmake -DC++11=OFF -DTESTS=OFF ..
    - make -j4 && sudo make install && cd ../..

