language: c

dist: trusty

compiler:
    - gcc
    - clang

env:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DUNITTEST_VERBOSE=ON ..
    - make all
    - make unittest

before_install:
    - script/ci_install.sh

