language: c

compiler:
    - gcc
    - clang

env:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCriterion_INCLUDE_DIR="${CRITERION_INCL}" -DCriterion_LIBRARY="${CRITERION_LIB}" ..
    - make all
    - ctest

addons:
    apt:
        sources:
            - kalakris-cmake
        packages:
            - cmake

before_install:
    # Criterion
    - export CRITERION_VERSION=1.2.1
    - wget https://github.com/Snaipe/Criterion/releases/download/v${CRITERION_VERSION}/criterion-${CRITERION_VERSION}-linux-x86_64.tar.bz2
    - tar xvjf criterion-${CRITERION_VERSION}-linux-x86_64.tar.bz2 
    - export CRITERION_INCL=$PWD/criterion-${CRITERION_VERSION}/include
    - export CRITERION_LIB=$PWD/criterion-${CRITERION_VERSION}/lib/libcriterion.a

after_failure:
    - cat Testing/Temporary/LastTest.log
