language: c

dist: trusty
sudo: required

addons:
  apt:
    packages:
        - valgrind

compiler:
    - gcc
    - clang

env:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DUNITTEST_VERBOSE=ON ..
    - make all
    - make unittest
    - valgrind --tool=memcheck --track-origins=yes src/bin/keygen -sl 5000 1> /dev/null

before_install:
    - script/ci_install.sh

