language: c

compiler:
    - gcc
    - clang

script:
    - mkdir build
    - cd build
    - cmake ..
    - make all
    - ctest

before_install:
    - sudo add-apt-repository --yes ppa:kalakris/cmake
    - sudo apt-get update -qq
    - sudo apt-get install -y cmake
