language: c

compiler:
    - gcc
    - clang

script:
    - mkdir build
    - cd build
    - cmake -DCriterion_INCLUDE_DIR="${CRITERION_INCL}" -DCriterion_LIBRARY="${CRITERION_LIB}" ..
    - make all
    - ctest

before_install:
    # CMake
    - sudo add-apt-repository --yes ppa:kalakris/cmake
    - sudo apt-get update -qq
    - sudo apt-get install -y cmake
    # Criterion
    - wget https://github.com/Snaipe/Criterion/releases/download/v1.2.0/criterion-1.2.0-linux-x86_64.tar.bz2
    - tar xvjf criterion-1.2.0-linux-x86_64.tar.bz2 
    - export CRITERION_INCL=$PWD/criterion-1.2.0/include
    - export CRITERION_LIB=$PWD/criterion-1.2.0/lib/libcriterion.a

