language: c

compiler:
    - gcc
    - clang

env:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCriterion_INCLUDE_DIR="${CRITERION_INCL}" -DCriterion_LIBRARY="${CRITERION_LIB}" ..
    - make all
    - ctest

before_install:
    # CMake
    - sudo add-apt-repository --yes ppa:kalakris/cmake
    - sudo apt-get update -qq
    - sudo apt-get install -y cmake
    # Criterion
    - wget https://github.com/Snaipe/Criterion/releases/download/v1.2.1/criterion-1.2.1-linux-x86_64.tar.bz2
    - tar xvjf criterion-1.2.1-linux-x86_64.tar.bz2 
    - export CRITERION_INCL=$PWD/criterion-1.2.1/include
    - export CRITERION_LIB=$PWD/criterion-1.2.1/lib/libcriterion.a

after_failure:
    - cat Testing/Temporary/LastTest.log
